local icons = {
    cmp = {
        Text          = "",
        Method        = "",
        Function      = "",
        Constructor   = "",
        Field         = "",
        Variable      = "",
        Class         = "",
        Interface     = "",
        Module        = "",
        Property      = "",
        Unit          = "",
        Value         = "",
        Enum          = "",
        Keyword       = "",
        Snippet       = "",
        Color         = "",
        File          = "",
        Reference     = "",
        Folder        = "",
        EnumMember    = "",
        Constant      = "",
        Struct        = "",
        Event         = "",
        Operator      = "",
        TypeParameter = "𝙏",
        Namespace     = "",
        Package       = "",
        String        = "",
        Number        = "",
        Boolean       = "",
        Array         = "",
        Object        = "",
        Null          = "",
        Parameter     = "",
        Associated    = "",
    },
    diagnostics = {
        error_sign = "",
        warn_sign  = "",
        hint_sign  = "",
        infor_sign = "",
        debug_sign = "",
        trace_sign = "",
    },

    todo = {
        fix  = "",
        todo = "",
        hack = "",
        warn = "ﱥ",
        perf = "",
        note = "",
    },
    file = {
        default = "",
        symlink = "",
        bookmark = ""
    },
    folder = {
        default = "",
        open = "",
        empty = "",
        empty_open = "",
        symlink = "",
        symlink_open = ""
    },
    arrow = {
        left = "",
        down = "",
        up = "",
        right = "",
        symlink = "",
        caret = "",
    },
    git = {
        unstaged = "✗",
        staged = "✓",
        unmerged = "",
        renamed = "➜",
        untracked = "",
        deleted = "",
        ignored = "◌",
    },
    dap = {
        breakpoint = "",
        breakpoint_condition = "",
        breakpoint_rejected = "",
        log_point = "ﯽ",
        stopped = "",

    },
    misc = {
        line_sep = "│",
        close = "",
        circle_dot = "●",
        pin = "車"
    }
}

return icons
